import {useState} from 'react';
import {formatDate,formatTime,type Agency,type ContactRecord,type DutyAssignment,type Cycle,type Snapshot} from '../lib/model';
type Run=(action:string,args:Record<string,unknown>,success:string)=>Promise<boolean>;
type Props={data:Snapshot;cycle?:Cycle;run:Run;busy:boolean;readOnly:boolean;dirty:(v:boolean)=>void};
const field=(f:FormData,name:string)=>String(f.get(name)||'');
const localTime=(date:string)=>{const d=new Date(date);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export default function Settings({data,cycle,run,busy,readOnly,dirty}:Props){
 const [agency,setAgency]=useState<Agency|null|undefined>();const [contact,setContact]=useState<ContactRecord|null|undefined>();const [assignment,setAssignment]=useState<DutyAssignment|null|undefined>();
 const [period,setPeriod]=useState<Cycle|null|undefined>();const [roster,setRoster]=useState<string[]>([]);
 const contacts=data.contacts||[];
 const editingConfig=agency!==undefined||contact!==undefined||assignment!==undefined||period!==undefined;
 const discard=()=>{if(window.confirm('Discard changes to this settings form?')){dirty(false);return true;}return false;};
 return <div className="settings">
 <details className="panel"><summary>Reporting agencies</summary><p>Active agencies are included in new periods. Use Reporting periods to adjust an existing week’s expected roster.</p>
 {agency!==undefined?<form key={agency?.id||'new'} onChange={()=>dirty(true)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run('agency',{id:agency?.id,version:agency?.version,name:field(f,'name'),county:field(f,'county'),active:f.get('active')==='on'},'Agency saved.'))setAgency(undefined);}}><fieldset disabled={busy||readOnly}><div className="fields two"><label>Agency name<input name="name" required maxLength={150} defaultValue={agency?.name}/></label><label>County<select name="county" defaultValue={agency?.county||'Klamath'}>{['Klamath','Lake','Harney','Modoc'].map(c=><option key={c}>{c}</option>)}</select></label></div><label className="check"><input name="active" type="checkbox" defaultChecked={agency?.active??true}/>Expected to report in new periods</label><div className="action-row"><button className="button primary">Save agency</button><button type="button" className="button" onClick={()=>{if(discard())setAgency(undefined);}}>Cancel</button></div></fieldset></form>:<><div className="settings-list">{data.agencies.map(a=><div key={a.id}><span><strong>{a.name}</strong><small>{a.county} · {a.active?'Expected to report':'Inactive'}</small></span><button className="text-button" disabled={readOnly||editingConfig} onClick={()=>setAgency(a)}>Edit agency</button></div>)}</div><button className="button" disabled={readOnly||editingConfig} onClick={()=>setAgency(null)}>Add agency</button></>}
 </details>
 <details className="panel"><summary>Duty chief rotation</summary><p>Set assignment dates and an optional backup. Changing an assignment updates the chief shown on open reporting periods; closed periods keep their history.</p>
 {assignment!==undefined?<form key={assignment?.id||'new'} onChange={()=>dirty(true)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run('rotation',{id:assignment?.id,version:assignment?.version,startDate:field(f,'start'),endDate:field(f,'end'),contactId:field(f,'contact'),backupContactId:field(f,'backup'),active:f.get('active')==='on'},'Duty assignment saved.'))setAssignment(undefined);}}><fieldset disabled={busy||readOnly}><div className="fields two"><label>Start date<input name="start" type="date" required defaultValue={assignment?.start_date}/></label><label>End date (leave blank for ongoing)<input name="end" type="date" defaultValue={assignment?.end_date||''}/></label><label>Duty chief<select name="contact" required defaultValue={assignment?.contact_id||''}><option value="">Select contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Backup<select name="backup" defaultValue={assignment?.backup_contact_id||''}><option value="">No backup assigned</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label className="check"><input name="active" type="checkbox" defaultChecked={assignment?.active??true}/>Active assignment</label><div className="action-row"><button className="button primary">Save assignment</button><button type="button" className="button" onClick={()=>{if(discard())setAssignment(undefined);}}>Cancel</button></div></fieldset></form>:<><div className="settings-list">{(data.rotation||[]).map(d=><div key={d.id}><span><strong>{contacts.find(c=>c.id===d.contact_id)?.name||'Unassigned'}</strong><small>{formatDate(d.start_date)} – {d.end_date?formatDate(d.end_date):'onward'}{!d.active?' · Inactive':''}{d.backup_contact_id?` · Backup: ${contacts.find(c=>c.id===d.backup_contact_id)?.name}`:''}</small></span><button className="text-button" disabled={readOnly||editingConfig} onClick={()=>setAssignment(d)}>Edit assignment</button></div>)}</div><button className="button" disabled={readOnly||editingConfig} onClick={()=>setAssignment(null)}>Add assignment</button></>}
 </details>
 <details className="panel"><summary>Reporting periods & deadlines</summary><p>Agency deadlines are entered in your local time. State reporting remains due before Monday at 10:00 a.m. Pacific.</p>
 {period!==undefined?<form key={period?.id||'new'} onChange={()=>dirty(true)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run(period?'period':'cycle',{id:period?.id,revision:period?.revision,startDate:field(f,'start'),endDate:field(f,'end'),dueAt:new Date(field(f,'due')).toISOString(),...(period?{agencyIds:roster}:{})},'Reporting period saved.'))setPeriod(undefined);}}><fieldset disabled={busy||readOnly}><div className="fields three"><label>Start date<input type="date" name="start" required defaultValue={period?.start_date}/></label><label>End date<input type="date" name="end" required defaultValue={period?.end_date}/></label><label>Agency deadline<input type="datetime-local" name="due" required defaultValue={period?localTime(period.due_at):''}/></label></div>{period&&<fieldset className="overhead-options"><legend>Expected agencies for this period</legend><div>{data.agencies.map(a=><label className="check" key={a.id}><input type="checkbox" checked={roster.includes(a.id)} onChange={e=>setRoster(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/>{a.name}</label>)}</div></fieldset>}<p className="muted">The duty chief comes from the rotation. Agencies with saved reports remain on the roster.</p><div className="action-row"><button className="button primary">Save period</button><button type="button" className="button" onClick={()=>{if(discard())setPeriod(undefined);}}>Cancel</button></div></fieldset></form>:<><div className="settings-list">{data.cycles.map(c=><div key={c.id}><span><strong>{formatDate(c.start_date)} – {formatDate(c.end_date)}</strong><small>{c.duty_name} · {c.closed?'Closed':'Open'} · Deadline {formatTime(c.due_at)}</small></span><div className="action-row"><button className="text-button" disabled={readOnly||busy||editingConfig} onClick={()=>{setPeriod(c);setRoster(c.roster.map(a=>a.id));}}>Edit period</button><button className="text-button" disabled={readOnly||busy||editingConfig} onClick={()=>run('close',{cycleId:c.id,revision:c.revision,closed:!c.closed},c.closed?'Period reopened.':'Period closed.')}>{c.closed?'Reopen':'Close'}</button></div></div>)}</div><button className="button" disabled={readOnly||editingConfig} onClick={()=>setPeriod(null)}>Add reporting period</button></>}
 </details>
 <details className="panel"><summary>Contacts</summary>
 {contact!==undefined?<form key={contact?.id||'new'} onChange={()=>dirty(true)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run('contact',{id:contact?.id,version:contact?.version,name:field(f,'name'),phone:field(f,'phone'),email:field(f,'email'),userId:field(f,'user'),active:f.get('active')==='on'},'Contact saved.'))setContact(undefined);}}><fieldset disabled={busy||readOnly}><div className="fields two"><label>Name<input name="name" required maxLength={150} defaultValue={contact?.name}/></label><label>Phone<input name="phone" type="tel" maxLength={80} defaultValue={contact?.phone}/></label><label>Email<input name="email" type="email" maxLength={254} defaultValue={contact?.email}/></label><label>Board account (optional)<select name="user" defaultValue={contact?.user_id||''}><option value="">Not linked</option>{data.context.members.map(m=><option key={m.id} value={m.id}>{m.email}</option>)}</select></label></div><label className="check"><input name="active" type="checkbox" defaultChecked={contact?.active??true}/>Active contact</label><div className="action-row"><button className="button primary">Save contact</button><button type="button" className="button" onClick={()=>{if(discard())setContact(undefined);}}>Cancel</button></div></fieldset></form>:<><div className="settings-list">{contacts.map(c=><div key={c.id}><span><strong>{c.name}</strong><small>{[c.phone,c.email].filter(Boolean).join(' · ')}</small></span><button className="text-button" disabled={readOnly||editingConfig} onClick={()=>setContact(c)}>Edit contact</button></div>)}</div><button className="button" disabled={readOnly||editingConfig} onClick={()=>setContact(null)}>Add contact</button></>}
 </details>
 <details className="panel"><summary>Change history</summary><div className="settings-list">{data.history.map(h=><div key={h.id}><span><strong>{({save:'Agency report corrected',shared_save:'Agency availability submitted',contact:'Contact updated',rotation:'Duty assignment updated',agency:'Agency updated',period:'Reporting period updated',cycle:'Reporting period opened',close:'Period closed or reopened',approve:'Summary approved',delivered:'OSFM submission recorded',reopen_review:'Summary reopened',duty_updated:'Duty chief updated'} as Record<string,string>)[h.action]||h.action}</strong><small>{formatTime(h.created_at)} · {data.context.members.find(m=>m.id===h.actor_id)?.email||'Board member'}</small>{h.agency_id&&<small>{data.agencies.find(a=>a.id===h.agency_id)?.name}</small>}<details><summary>Saved values</summary>{h.payload?.before!=null&&<><h4>Before</h4><SavedValues value={h.payload.before}/></>}<h4>Saved</h4><SavedValues value={h.payload?.result||h.payload?.input?.payload}/></details></span></div>)}</div>{!data.history.length&&<p>{readOnly?'Live history is not loaded.':'No changes recorded yet.'}</p>}</details>
 </div>;
}

function SavedValues({value}:{value:unknown}){
 if(value==null)return <p>No additional values.</p>;
 if(typeof value!=='object')return <p>{String(value)}</p>;
 const record=value as Record<string,unknown>;
 if(record.payload)return <SavedValues value={record.payload}/>;
 const titles:Record<string,string>={type1:'Type 1 engines',type3:'Type 3 engines',type6:'Type 6 engines',tender:'Water tenders',simultaneous:'Can deploy together',qualified:'Qualified leaders',trainees:'Trainees',extraCrew:'Additional personnel',prepo:'Prepositioning / IR',conflag:'In-state',outOfState:'Out-of-state',leaderDetails:'Leader information',crewDetails:'Crew qualifications',contactName:'Submitted by',contactPhone:'Phone',contactEmail:'Email',teams:'Task forces / strike teams',reason:'Reason / review notes',confirmed:'Confirmed',name:'Name',phone:'Phone',email:'Email',active:'Active',county:'County',start_date:'Start date',end_date:'End date',due_at:'Deadline',duty_name:'Duty chief',notes:'Notes',overhead:'Overhead qualifications',closed:'Closed',roster:'Expected agencies',reference:'OSFM confirmation'};
 const rows=Object.entries(record).filter(([k])=>k in titles);
 return <dl className="saved-values">{rows.map(([k,v])=><div key={k}><dt>{titles[k]}</dt><dd>{Array.isArray(v)?v.map(x=>typeof x==='object'&&x?x.name||'':String(x)).filter(Boolean).join(', '):typeof v==='boolean'?(v?'Yes':'No'):v==null||v===''?'Not set':String(v)}</dd></div>)}</dl>;
}
