import {equipment,labels,formatTime,type Snapshot,type Cycle} from '../lib/model';
import {weeklyHistory,type ArchivedReport} from '../lib/weekly-history';
const value=(v:unknown)=>v==null||v===''?'Not recorded':typeof v==='boolean'?(v?'Yes':'No'):String(v);
function Details({report}:{report:ArchivedReport}){return <dl className="saved-values">{Object.entries(report.raw).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{value(v)}</dd></div>)}</dl>;}
export default function WeeklyHistory({data,cycle,osfm=false}:{data:Snapshot;cycle:Cycle;osfm?:boolean}){
 const s=weeklyHistory(cycle,data,osfm);
 return <>
 {osfm&&<p className="notice">Klamath/Lake reported equipment. Harney reports are excluded. OSFM approval and submission are not recorded by these historical reports.</p>}
 <section className="overview-grid"><div className="completion panel"><div className="eyebrow">AGENCY REPORTS</div><div className="completion-number">{s.included.length}</div><h2>Agencies reported</h2><p>Latest submission per agency for this reporting week.</p><span className="badge">{s.rows.length} original reports</span></div><div className="totals panel"><div className="eyebrow">SUBMITTED EQUIPMENT OPTIONS</div><h2>Resources at a glance</h2><div className="equipment-grid">{equipment.map(k=><div key={k}><strong>{s.totals[k]??'—'}</strong><span>{labels[k]}{s.issues.some(i=>i.field===k)?' · Needs review':s.totals[k]===null?' · Not recorded for every agency':''}</span></div>)}</div><p>Can deploy together: <strong>{value(s.simultaneous)}</strong></p><div className="overhead"><span>Qualified leaders: <strong>{value(s.qualified)}</strong></span><span>Trainees: <strong>{value(s.trainees)}</strong></span><span>Extra crew: <strong>{value(s.extraCrew)}</strong></span></div></div></section>
 {s.issues.length>0&&<section className="notice warning"><strong>Equipment counts need review.</strong><p>The original values below fall outside the form’s count range. Affected totals are withheld.</p>{s.issues.map(i=><p key={`${i.agency}-${i.field}`}>{i.agency} · {labels[i.field]}: {i.value}</p>)}</section>}
 <section className="panel agency-table"><div className="section-top"><div><h2>Agency reporting</h2><p>Open a report to see the original answers and earlier submissions.</p></div></div><div className="table-scroll"><table><thead><tr><th>Agency</th>{equipment.map(k=><th key={k}>{labels[k]}</th>)}<th>Last submission</th></tr></thead><tbody>{s.included.map(r=><tr key={r.agency.id}><td><strong>{r.agency.name}</strong><small>{r.agency.county} County</small></td>{equipment.map(k=><td key={k}>{value(r.counts[k])}</td>)}<td>{r.live?formatTime(r.row.source_created_at!):r.row.source_created_at?.replace('T',' ').slice(0,16)}</td></tr>)}</tbody></table></div></section>
 <section className="panel archive-list"><h2>Report details</h2>{s.included.map(r=><details key={r.agency.id}><summary><strong>{r.agency.name}</strong><span>{r.row.submitted_by||'Name not recorded'} · {r.live?formatTime(r.row.source_created_at!):r.row.source_created_at?.replace('T',' ').slice(0,16)}</span></summary><Details report={r.row}/>{r.versions.filter(v=>v.id!==r.row.id).length>0&&<details><summary>Earlier submissions · {r.versions.filter(v=>v.id!==r.row.id).length}</summary>{r.versions.filter(v=>v.id!==r.row.id).map(v=><article key={v.id}><h3>{v.source_created_at?.replace('T',' ').slice(0,16)} · {v.submitted_by||'Name not recorded'}</h3><Details report={v}/></article>)}</details>}</details>)}</section>
 {s.unassigned.length>0&&<section className="panel archive-list"><h2>Reports without a matched agency · {s.unassigned.length}</h2><p>These reports are preserved here and excluded from agency totals.</p>{s.unassigned.map(r=><details key={r.id}><summary>{r.agency_name||'Agency not provided'} · {r.submitted_by||'Name not recorded'}</summary><Details report={r}/></details>)}</section>}
 </>;
}
