import { createBrowserSupabase, getSessionOrNull, hasConfig } from "/shared/lib/supabase-client.js";
import { verifyPlatformAdmin } from "/client-portal/admin-access.js";
import { renderAdminNavigation } from "/account/admin/admin-navigation.js?v=10";
const list = document.querySelector("#application-list"), detail = document.querySelector("#application-detail"), summary = document.querySelector("#application-summary"), dialog = document.querySelector("#application-dialog"), manualForm = document.querySelector("#manual-application-form");
let supabase, applications = [], notes = [], selectedId = "", activeFilter = "active";
const activeStatuses = new Set(["new","reviewing","contacted","interviewing"]);
const esc = (value="") => String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const date = (value) => value ? new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "—";
const statusLabel = (value) => String(value || "").replaceAll("_"," ").replace(/\b\w/g, c=>c.toUpperCase());
const safeLink = (value, label) => { try { const url = new URL(value); return ["http:","https:"].includes(url.protocol) ? `<a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>` : ""; } catch { return ""; } };
function renderList(){ const visible = applications.filter(a => activeFilter === "all" || activeFilter === "active" ? activeStatuses.has(a.status) : a.status === activeFilter); summary.textContent = `${visible.length} ${activeFilter === "all" ? "total" : "matching"} application${visible.length === 1 ? "" : "s"}`; list.innerHTML = visible.length ? visible.map(a=>`<button class="application-card ${a.id===selectedId?"selected":""}" data-id="${a.id}"><span class="status ${esc(a.status)}">${esc(statusLabel(a.status))}</span><strong>${esc(a.full_name)}</strong><small>${esc(a.role_interest.replaceAll("_"," "))}</small><time>${date(a.created_at)}</time></button>`).join("") : '<p class="empty">No applications here.</p>'; }
function renderDetail(){ const a = applications.find(row=>row.id===selectedId); if(!a){detail.innerHTML='<p class="empty">Select an application to see the applicant profile, linked account, and private notes.</p>';return;} const appNotes=notes.filter(n=>n.application_id===a.id); detail.innerHTML=`<header class="detail-head"><div><span class="status ${esc(a.status)}">${esc(statusLabel(a.status))}</span><h2>${esc(a.full_name)}</h2><p>${esc(a.role_interest.replaceAll("_"," "))} · Submitted ${date(a.created_at)}</p></div><label>Status<select id="application-status">${["new","reviewing","contacted","interviewing","talent_pool","declined","hired"].map(s=>`<option value="${s}" ${a.status===s?"selected":""}>${statusLabel(s)}</option>`).join("")}</select></label></header><section class="profile-grid"><div><span>Email</span><a href="mailto:${esc(a.email)}">${esc(a.email)}</a></div><div><span>Account</span><strong>${a.account_user_id ? "Connected" : "No account connected"}</strong></div><div><span>Location / timezone</span><strong>${esc(a.location_timezone || "Not provided")}</strong></div><div><span>Availability</span><strong>${esc(a.availability || "Not provided")}</strong></div><div><span>Work arrangement</span><strong>${esc(statusLabel(a.work_arrangement))}</strong></div><div><span>Links</span>${[safeLink(a.portfolio_url,"Portfolio"),safeLink(a.github_url,"GitHub"),safeLink(a.cv_url,"CV / résumé"),a.cv_storage_path ? '<span id="uploaded-cv">Loading uploaded CV…</span>' : "",safeLink(a.source_url,"Original conversation")].filter(Boolean).join(" · ") || "Not provided"}</div></section><section class="message"><p>Application message</p><div>${esc(a.message).replaceAll("\n","<br>")}</div></section><section class="notes"><header><div><p>Private notes</p><h3>Conversation &amp; review history</h3></div></header><form id="note-form"><textarea name="body" rows="4" required placeholder="Add an internal note, paste a message, or record the next step."></textarea><input name="source_url" type="url" placeholder="Optional source link, e.g. Facebook conversation"><button>Add note</button></form><div class="note-timeline">${appNotes.length ? appNotes.map(n=>`<article><time>${date(n.created_at)}</time><p>${esc(n.body).replaceAll("\n","<br>")}</p>${safeLink(n.source_url,"Open source")}</article>`).join("") : '<p class="empty">No private notes yet.</p>'}</div></section>`; document.querySelector("#application-status").addEventListener("change", async e=>{await updateApplication(a.id,{status:e.target.value});}); document.querySelector("#note-form").addEventListener("submit",addNote); if(a.cv_storage_path) loadUploadedCv(a); }
async function loadUploadedCv(application) { const target = document.querySelector("#uploaded-cv"); const { data, error } = await supabase.storage.from("careers-files").createSignedUrl(application.cv_storage_path, 600, { download: application.cv_filename || "resume" }); if (!target) return; target.outerHTML = !error && data?.signedUrl ? `<a href="${esc(data.signedUrl)}" target="_blank" rel="noopener noreferrer">${esc(application.cv_filename || "Uploaded CV")}</a>` : "Uploaded CV unavailable"; }
async function load(){const [apps, noteRows] = await Promise.all([supabase.from("careers_applications").select("*").order("created_at",{ascending:false}), supabase.from("careers_application_notes").select("*").order("created_at",{ascending:false})]); if(apps.error)throw apps.error;if(noteRows.error)throw noteRows.error; applications=apps.data||[];notes=noteRows.data||[];if(!selectedId&&applications[0])selectedId=applications[0].id;renderList();renderDetail();}
async function updateApplication(id,payload){const {error}=await supabase.from("careers_applications").update(payload).eq("id",id);if(error){alert(error.message);return;}await load();}
async function addNote(event){event.preventDefault();const form=event.currentTarget,fd=new FormData(form);const {error}=await supabase.from("careers_application_notes").insert({application_id:selectedId,body:String(fd.get("body")||"").trim(),source_url:String(fd.get("source_url")||"").trim()||null});if(error){alert(error.message);return;}form.reset();await load();}
list.addEventListener("click",e=>{const card=e.target.closest("[data-id]");if(!card)return;selectedId=card.dataset.id;renderList();renderDetail();});document.querySelector("#application-filters").addEventListener("click",e=>{const button=e.target.closest("button[data-filter]");if(!button)return;activeFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("selected",b===button));renderList();});document.querySelector("#add-application").addEventListener("click",()=>dialog.showModal());document.querySelector("#cancel-dialog").addEventListener("click",()=>dialog.close());manualForm.addEventListener("submit",async event=>{event.preventDefault();const fd=new FormData(manualForm), payload=Object.fromEntries(fd.entries());payload.work_arrangement="flexible";payload.status="new";const {data,error}=await supabase.from("careers_applications").insert(payload).select().single();if(error){alert(error.message);return;}selectedId=data.id;dialog.close();manualForm.reset();await load();});document.querySelector("#sign-out").addEventListener("click",()=>supabase.auth.signOut().then(()=>location.assign("/account/")));
async function start(){if(!hasConfig())throw new Error("Supabase is not configured.");supabase=createBrowserSupabase();const session=await getSessionOrNull(supabase);if(!session){location.replace("/account/?next=%2Faccount%2Fadmin%2Fapplications%2F");return;}if(!await verifyPlatformAdmin(supabase,session.user))throw new Error("You do not have application administration access.");renderAdminNavigation();await load();} start().catch(error=>{summary.textContent=error.message||"Unable to open applications.";});
