// Run against a disposable in-memory PostgreSQL runtime, never production.
// RA_PGLITE_PATH may point to a temporary pinned @electric-sql/pglite installation.
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.RA_PGLITE_PATH?pathToFileURL(process.env.RA_PGLITE_PATH).href:'@electric-sql/pglite');
const db=new PGlite();
const org='f30f90e6-c13b-4142-a258-9e93d2ba5f12';
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create table auth.users(id uuid primary key,email text);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
create table public.organizations(id uuid primary key,name text,owner_user_id uuid,account_status text);
create table public.organization_memberships(organization_id uuid,user_id uuid,role text);
create function public.is_platform_admin() returns boolean language sql stable as $$select auth.uid()='${uid(9)}'::uuid$$;
create function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
grant select on public.organizations,public.organization_memberships to authenticated;
insert into auth.users values ${[1,2,3,4,5,9].map(n=>`('${uid(n)}','person${n}@example.com')`).join(',')};
insert into public.organizations values('${org}','Klamath County Fire Defense Board','${uid(1)}','active');
insert into public.organization_memberships values('${org}','${uid(2)}','editor'),('${org}','${uid(3)}','editor'),('${org}','${uid(5)}','editor');`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260905215808_organization_private_products.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../../supabase/migrations/20260906005357_resource_availability.sql',import.meta.url),'utf8'));
const w=(await db.query('select id from public.ra_workspaces')).rows[0].id;
assert.equal((await db.query('select count(*)::int as n from public.ra_agencies')).rows[0].n,25);
assert.equal((await db.query("select duty_name from public.ra_cycles where start_date='2026-08-31'")).rows[0].duty_name,'Matt Chavarria');
await db.exec('delete from public.ra_cycles;delete from public.ra_agencies');
const as=async n=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?uid(n):'']);await db.exec(`set role ${n?'authenticated':'anon'}`);};
const root=async sql=>{await db.exec('reset role');return db.exec(sql);};
const cmd=async(action,args)=> (await db.query('select public.ra_command($1,$2,$3::jsonb) as result',[w,action,JSON.stringify(args)])).rows[0].result;
let checks=0;const denied=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++;};
const form=(values={})=>({type1:0,type3:0,type6:0,tender:0,qualified:0,trainees:0,extraCrew:0,simultaneous:0,prepo:false,conflag:false,outOfState:false,notes:'',leaderDetails:'',contactName:'Demo',contactPhone:'541-555-0100',contactEmail:'demo@example.com',teams:0,reason:'',confirmed:false,...values});
await as(2);assert.equal((await db.query('select * from public.ra_workspaces')).rows.length,0);checks++;
await as(9);assert.equal((await db.query('select * from public.ra_workspaces')).rows.length,1);checks++;
await root(`update public.organization_private_products set status='active' where id='${w}'`);
await as(1);
const a=await cmd('agency',{name:'Agency One',county:'Klamath'});const b=await cmd('agency',{name:'Agency Two',county:'Lake'});
await cmd('assign',{agencyId:a.id,userId:uid(2),enabled:true});await cmd('assign',{agencyId:b.id,userId:uid(3),enabled:true});
await cmd('reviewer',{userId:uid(5),enabled:true});
const c=await cmd('cycle',{startDate:'2026-09-07',endDate:'2026-09-13',dueAt:'2026-09-07T16:00:00Z',dutyName:'Demo duty chief'});
await as(2);
assert.equal((await db.query('select * from public.ra_agencies')).rows.length,2);checks++;
const agencySnapshot=(await db.query('select public.ra_snapshot($1) as data',[w])).rows[0].data;
assert.equal(agencySnapshot.agencies.length,2);assert.equal(agencySnapshot.context.admin,false);assert.equal(agencySnapshot.context.members.length,0);checks+=3;
await denied(()=>cmd('save',{cycleId:c.id,agencyId:b.id,version:0,payload:form(),submit:true}),/not assigned/);
await denied(()=>cmd('agency',{name:'Forbidden',county:'Lake'}),/administrator/);
await denied(()=>cmd('reviewer',{userId:uid(2),enabled:true}),/administrator/);
await denied(()=>db.query('insert into public.ra_responses(workspace_id) values($1)',[w]),/permission denied/);
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:0,payload:form({type1:1.5}),submit:true}),/whole number/);
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:0,payload:form({qualified:1}),submit:true}),/leader names/);
const p=form({type1:1,type6:1,simultaneous:1,qualified:1,trainees:1,leaderDetails:'Leader and trainee',notes:'Shared crew'});
const r=await cmd('save',{cycleId:c.id,agencyId:a.id,version:0,payload:p,submit:true});assert.equal(r.version,1);checks++;
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:0,payload:p,submit:true}),/changed/);
await as(3);assert.equal((await db.query('select * from public.ra_responses')).rows.length,0);checks++;
await as(4);assert.equal((await db.query('select * from public.ra_cycles')).rows.length,0);checks++;
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:1,payload:p,submit:true}),/access denied/);
await as(5);assert.equal((await db.query('select * from public.ra_responses')).rows.length,1);checks++;
const reviewerSnapshot=(await db.query('select public.ra_snapshot($1) as data',[w])).rows[0].data;
assert.equal(reviewerSnapshot.context.reviewer,true);assert.equal(reviewerSnapshot.responses.length,1);assert.equal(reviewerSnapshot.cycles[0].revision,1);checks+=3;
await denied(()=>cmd('assign',{agencyId:a.id,userId:uid(5),enabled:true}),/administrator/);
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:1,payload:p,submit:true}),/not assigned/);
await denied(()=>cmd('approve',{cycleId:c.id,revision:0,payload:form()}),/changed/);
const review=form({type1:1,qualified:1,teams:1,confirmed:true});
await denied(()=>cmd('approve',{cycleId:c.id,revision:1,payload:review}),/Explain missing/);
review.reason='Agency Two has not reported. Select one staffed engine.';
await denied(()=>cmd('approve',{cycleId:c.id,revision:1,payload:{...review,type6:1}}),/simultaneous/);
await denied(()=>cmd('approve',{cycleId:c.id,revision:1,payload:{...review,qualified:2}}),/exceeds submitted/);
const ap=await cmd('approve',{cycleId:c.id,revision:1,payload:review});assert.equal(ap.snapshot.missing,1);checks++;
await as(2);assert.equal((await db.query('select * from public.ra_approvals')).rows.length,0);checks++;
await cmd('save',{cycleId:c.id,agencyId:a.id,version:1,payload:p,submit:true});
await as(5);await denied(()=>cmd('delivered',{cycleId:c.id,revision:2,approvalId:ap.id,reference:'Ref'}),/current approval/);
await as(3);await cmd('save',{cycleId:c.id,agencyId:b.id,version:0,payload:form(),submit:true});
await as(5);const ap2=await cmd('approve',{cycleId:c.id,revision:3,payload:review});assert.equal(ap2.snapshot.missing,0);checks++;
await cmd('delivered',{cycleId:c.id,revision:3,approvalId:ap2.id,reference:'Manual confirmation DEMO'});
await denied(()=>cmd('delivered',{cycleId:c.id,revision:3,approvalId:ap2.id,reference:'Duplicate'}),/duplicate key/);
await cmd('reopen_review',{cycleId:c.id,revision:3});
await denied(()=>cmd('delivered',{cycleId:c.id,revision:4,approvalId:ap2.id,reference:'Old approval'}),/current approval/);
assert.equal((await db.query('select snapshot from public.ra_approvals where id=$1',[ap2.id])).rows[0].snapshot.responses.length,2);checks++;
await cmd('close',{cycleId:c.id,revision:4,closed:true});await as(2);
await denied(()=>cmd('save',{cycleId:c.id,agencyId:a.id,version:2,payload:p,submit:true}),/closed/);
await root(`update public.organization_private_products set status='paused' where id='${w}'`);await as(1);
assert.equal((await db.query('select * from public.ra_responses')).rows.length,0);checks++;
await denied(()=>cmd('cycle',{startDate:'2026-09-14'}),/access denied/);
await root(`update public.organization_private_products set status='active' where id='${w}';delete from public.organization_memberships where user_id='${uid(2)}'`);await as(2);
assert.equal((await db.query('select * from public.ra_responses')).rows.length,0);checks++;
await as(null);await denied(()=>db.query('select * from public.ra_workspaces'),/permission denied/);await denied(()=>cmd('cycle',{}),/permission denied/);
await denied(()=>db.query('select public.ra_snapshot($1)',[w]),/permission denied/);
await root(`insert into public.organizations values('${uid(20)}','Other Organization','${uid(4)}','active');
insert into public.organization_private_products(id,organization_id,name,app_path,status) values('${uid(21)}','${uid(20)}','Resource Availability','/resource-availability/','active');
insert into public.ra_workspaces values('${uid(21)}','${uid(20)}','Other Organization');`);
await as(1);await denied(()=>db.query('select public.ra_command($1,$2,$3)',[uid(21),'agency','{"name":"Forbidden","county":"Lake"}']),/access denied/);
await denied(()=>db.query('select public.ra_snapshot($1)',[uid(21)]),/access denied/);
await root(`update public.organizations set account_status='inactive' where id='${org}'`);await as(1);
assert.equal((await db.query('select * from public.ra_responses')).rows.length,0);checks++;
await root(`update public.organizations set account_status='active' where id='${org}'`);
await root(`update public.organization_private_products set app_path='/another-app/' where id='${w}'`);await as(1);
assert.equal((await db.query('select * from public.ra_workspaces')).rows.length,0);checks++;
await root('select 1');
assert.equal((await db.query("select count(*)::int as n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname like 'ra_%' and c.relkind='r' and not c.relrowsecurity")).rows[0].n,0);checks++;
assert.equal((await db.query("select count(*)::int as n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'ra_%' and p.prosecdef")).rows[0].n,0);checks++;

// Shared intake needs organization membership, not an agency assignment.
await root(`update public.organization_private_products set app_path='/resource-availability/' where id='${w}'`);
await as(1);
const dates=(await db.query("select ((now() at time zone 'America/Los_Angeles')::date)::text as today")).rows[0];
await root(`update public.ra_cycles set start_date='${dates.today}',end_date='${dates.today}',closed=false where id='${c.id}'`);
await as(5);
const shared=await cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form({contactPhone:'',contactEmail:'',crewDetails:'2 FF1',extraCrew:2,overhead:['Safety']}),submit:true});
assert.equal(shared.payload.extraCrew,2);checks++;
const again=await cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form({contactPhone:'',contactEmail:''}),submit:true});
assert.equal(again.version,shared.version+1);checks++;
assert.equal((await db.query('select count(*)::int as n from public.ra_responses where agency_id=$1',[a.id])).rows[0].n,1);checks++;
await denied(()=>cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form({overhead:'Safety'}),submit:true}),/overhead/);
await denied(()=>cmd('shared_save',{cycleId:c.id,agencyId:uid(99),payload:form(),submit:true}),/roster/);
await as(4);await denied(()=>cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form(),submit:true}),/access denied/);
await as(null);await denied(()=>cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form(),submit:true}),/permission denied/);
await as(1);const harney=await cmd('agency',{name:'Harney test agency',county:'Harney'});
await root(`update public.ra_cycles set roster=roster || jsonb_build_array(jsonb_build_object('id','${harney.id}','name','Harney test agency','county','Harney')) where id='${c.id}'`);
await as(5);await cmd('shared_save',{cycleId:c.id,agencyId:harney.id,payload:form({type1:9,simultaneous:9}),submit:true});
const rev=(await db.query('select revision from public.ra_cycles where id=$1',[c.id])).rows[0].revision;
await denied(()=>cmd('approve',{cycleId:c.id,revision:rev,payload:form({type1:9,confirmed:true})}),/exceeds submitted/);
const scoped=await cmd('approve',{cycleId:c.id,revision:rev,payload:form({confirmed:true})});
assert.equal(scoped.snapshot.roster.length,2);checks++;
assert.equal(scoped.snapshot.responses.length,2);checks++;
await root(`update public.ra_cycles set start_date='2099-01-01',end_date='2099-01-07' where id='${c.id}'`);await as(5);
await denied(()=>cmd('shared_save',{cycleId:c.id,agencyId:a.id,payload:form(),submit:true}),/current reporting/);
console.log(`${checks} PostgreSQL workflow and authorization checks passed.`);
await db.close();
