create table if not exists public.client_websites (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  live_url text,
  status text not null default 'active',
  created_by_user_id uuid references auth.users (id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint client_websites_slug_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint client_websites_status_check check (status in ('draft', 'active', 'paused', 'archived'))
);

create table if not exists public.website_members (
  id uuid primary key default gen_random_uuid(),
  website_id uuid not null references public.client_websites (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'viewer',
  status text not null default 'active',
  invited_by_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_members_unique unique (website_id, user_id),
  constraint website_members_role_check check (role in ('owner', 'editor', 'viewer')),
  constraint website_members_status_check check (status in ('active', 'revoked'))
);

create table if not exists public.website_assets (
  id uuid primary key default gen_random_uuid(),
  website_id uuid not null references public.client_websites (id) on delete cascade,
  asset_key text not null,
  label text not null,
  category text not null default 'image',
  replacement_type text not null default 'html_src',
  source_file text,
  target_selector text,
  alt_text text,
  expected_aspect_ratio text,
  focal_point_x numeric(5, 2) not null default 50,
  focal_point_y numeric(5, 2) not null default 50,
  current_version_id uuid,
  status text not null default 'active',
  created_by_user_id uuid references auth.users (id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_assets_unique_key unique (website_id, asset_key),
  constraint website_assets_key_check check (asset_key ~ '^[a-z][a-zA-Z0-9._-]*$'),
  constraint website_assets_category_check check (category in ('image', 'logo', 'document', 'brand', 'social', 'other')),
  constraint website_assets_replacement_type_check check (replacement_type in ('html_src', 'css_background', 'carousel_slide', 'metadata', 'download_only')),
  constraint website_assets_focal_x_check check (focal_point_x between 0 and 100),
  constraint website_assets_focal_y_check check (focal_point_y between 0 and 100),
  constraint website_assets_status_check check (status in ('active', 'archived'))
);

create table if not exists public.website_asset_versions (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references public.website_assets (id) on delete cascade,
  version_number integer not null,
  status text not null default 'draft',
  storage_bucket text not null default 'website-assets-private',
  storage_path text not null,
  public_url text,
  original_filename text not null,
  mime_type text,
  size_bytes bigint,
  width integer,
  height integer,
  change_note text,
  uploaded_by_user_id uuid references auth.users (id) on delete set null default auth.uid(),
  approved_by_user_id uuid references auth.users (id) on delete set null,
  published_by_user_id uuid references auth.users (id) on delete set null,
  approved_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_asset_versions_unique_version unique (asset_id, version_number),
  constraint website_asset_versions_unique_storage unique (storage_bucket, storage_path),
  constraint website_asset_versions_number_check check (version_number > 0),
  constraint website_asset_versions_status_check check (status in ('draft', 'pending_review', 'approved', 'published', 'rejected', 'archived')),
  constraint website_asset_versions_bucket_check check (storage_bucket in ('website-assets-private', 'website-assets-public')),
  constraint website_asset_versions_size_check check (size_bytes is null or size_bytes >= 0),
  constraint website_asset_versions_width_check check (width is null or width > 0),
  constraint website_asset_versions_height_check check (height is null or height > 0)
);

alter table public.website_assets drop constraint if exists website_assets_current_version_id_fkey;
alter table public.website_assets add constraint website_assets_current_version_id_fkey foreign key (current_version_id) references public.website_asset_versions (id) on delete set null;

create table if not exists public.website_asset_activity (
  id bigint generated by default as identity primary key,
  website_id uuid not null references public.client_websites (id) on delete cascade,
  asset_id uuid references public.website_assets (id) on delete cascade,
  version_id uuid references public.website_asset_versions (id) on delete cascade,
  actor_user_id uuid references auth.users (id) on delete set null default auth.uid(),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint website_asset_activity_details_check check (jsonb_typeof(details) = 'object')
);

create index if not exists website_members_user_status_idx on public.website_members (user_id, status, website_id);
create index if not exists website_assets_website_status_idx on public.website_assets (website_id, status, updated_at desc);
create index if not exists website_asset_versions_asset_created_idx on public.website_asset_versions (asset_id, created_at desc);
create index if not exists website_asset_versions_status_created_idx on public.website_asset_versions (status, created_at desc);
create index if not exists website_asset_activity_website_created_idx on public.website_asset_activity (website_id, created_at desc);

create or replace function public.website_member_role(target_website_id uuid)
returns text language sql stable security definer set search_path = public as $$
  select wm.role from public.website_members wm
  where wm.website_id = target_website_id and wm.user_id = auth.uid() and wm.status = 'active' limit 1;
$$;

create or replace function public.can_view_client_website(target_website_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_platform_admin() or exists (
    select 1 from public.website_members wm
    where wm.website_id = target_website_id and wm.user_id = auth.uid() and wm.status = 'active'
  );
$$;

create or replace function public.can_edit_client_website(target_website_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_platform_admin() or exists (
    select 1 from public.website_members wm
    where wm.website_id = target_website_id and wm.user_id = auth.uid() and wm.status = 'active' and wm.role in ('owner', 'editor')
  );
$$;

create or replace function public.can_manage_client_website(target_website_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_platform_admin() or exists (
    select 1 from public.website_members wm
    where wm.website_id = target_website_id and wm.user_id = auth.uid() and wm.status = 'active' and wm.role = 'owner'
  );
$$;

create or replace function public.website_storage_path_id(object_name text)
returns uuid language plpgsql immutable set search_path = public as $$
declare first_segment text;
begin
  first_segment := split_part(coalesce(object_name, ''), '/', 1);
  if first_segment !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return null; end if;
  return first_segment::uuid;
exception when invalid_text_representation then return null;
end;
$$;

create or replace function public.next_website_asset_version_number(target_asset_id uuid)
returns integer language sql stable security invoker set search_path = public as $$
  select coalesce(max(wav.version_number), 0) + 1 from public.website_asset_versions wav where wav.asset_id = target_asset_id;
$$;

revoke all on function public.website_member_role(uuid) from public;
revoke all on function public.can_view_client_website(uuid) from public;
revoke all on function public.can_edit_client_website(uuid) from public;
revoke all on function public.can_manage_client_website(uuid) from public;
revoke all on function public.website_storage_path_id(text) from public;
revoke all on function public.next_website_asset_version_number(uuid) from public;
grant execute on function public.website_member_role(uuid) to authenticated;
grant execute on function public.can_view_client_website(uuid) to authenticated;
grant execute on function public.can_edit_client_website(uuid) to authenticated;
grant execute on function public.can_manage_client_website(uuid) to authenticated;
grant execute on function public.website_storage_path_id(text) to authenticated;
grant execute on function public.next_website_asset_version_number(uuid) to authenticated;

drop trigger if exists client_websites_set_updated_at on public.client_websites;
create trigger client_websites_set_updated_at before update on public.client_websites for each row execute function public.set_updated_at();
drop trigger if exists website_members_set_updated_at on public.website_members;
create trigger website_members_set_updated_at before update on public.website_members for each row execute function public.set_updated_at();
drop trigger if exists website_assets_set_updated_at on public.website_assets;
create trigger website_assets_set_updated_at before update on public.website_assets for each row execute function public.set_updated_at();
drop trigger if exists website_asset_versions_set_updated_at on public.website_asset_versions;
create trigger website_asset_versions_set_updated_at before update on public.website_asset_versions for each row execute function public.set_updated_at();

alter table public.client_websites enable row level security;
alter table public.website_members enable row level security;
alter table public.website_assets enable row level security;
alter table public.website_asset_versions enable row level security;
alter table public.website_asset_activity enable row level security;

revoke all on public.client_websites from anon;
revoke all on public.website_members from anon;
revoke all on public.website_assets from anon;
revoke all on public.website_asset_versions from anon;
revoke all on public.website_asset_activity from anon;
grant select, insert, update, delete on public.client_websites to authenticated;
grant select, insert, update, delete on public.website_members to authenticated;
grant select, insert, update on public.website_assets to authenticated;
grant select, insert, update, delete on public.website_asset_versions to authenticated;
grant select on public.website_asset_activity to authenticated;
grant all on public.client_websites to service_role;
grant all on public.website_members to service_role;
grant all on public.website_assets to service_role;
grant all on public.website_asset_versions to service_role;
grant all on public.website_asset_activity to service_role;
grant usage, select on sequence public.website_asset_activity_id_seq to service_role;

drop policy if exists "client_websites_select" on public.client_websites;
create policy "client_websites_select" on public.client_websites for select to authenticated using (public.can_view_client_website(id));
drop policy if exists "client_websites_insert_admin" on public.client_websites;
create policy "client_websites_insert_admin" on public.client_websites for insert to authenticated with check (public.is_platform_admin() and created_by_user_id = auth.uid());
drop policy if exists "client_websites_update_admin" on public.client_websites;
create policy "client_websites_update_admin" on public.client_websites for update to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists "client_websites_delete_admin" on public.client_websites;
create policy "client_websites_delete_admin" on public.client_websites for delete to authenticated using (public.is_platform_admin());

drop policy if exists "website_members_select" on public.website_members;
create policy "website_members_select" on public.website_members for select to authenticated using (user_id = auth.uid() or public.can_manage_client_website(website_id));
drop policy if exists "website_members_insert_manager" on public.website_members;
create policy "website_members_insert_manager" on public.website_members for insert to authenticated with check (public.can_manage_client_website(website_id) and invited_by_user_id = auth.uid());
drop policy if exists "website_members_update_manager" on public.website_members;
create policy "website_members_update_manager" on public.website_members for update to authenticated using (public.can_manage_client_website(website_id)) with check (public.can_manage_client_website(website_id));
drop policy if exists "website_members_delete_manager" on public.website_members;
create policy "website_members_delete_manager" on public.website_members for delete to authenticated using (public.can_manage_client_website(website_id));

drop policy if exists "website_assets_select" on public.website_assets;
create policy "website_assets_select" on public.website_assets for select to authenticated using (public.can_view_client_website(website_id));
drop policy if exists "website_assets_insert" on public.website_assets;
create policy "website_assets_insert" on public.website_assets for insert to authenticated with check (public.can_edit_client_website(website_id) and created_by_user_id = auth.uid());
drop policy if exists "website_assets_update" on public.website_assets;
create policy "website_assets_update" on public.website_assets for update to authenticated using (public.can_edit_client_website(website_id)) with check (public.can_edit_client_website(website_id));

drop policy if exists "website_asset_versions_select" on public.website_asset_versions;
create policy "website_asset_versions_select" on public.website_asset_versions for select to authenticated using (exists (select 1 from public.website_assets wa where wa.id = website_asset_versions.asset_id and public.can_view_client_website(wa.website_id)));
drop policy if exists "website_asset_versions_insert" on public.website_asset_versions;
create policy "website_asset_versions_insert" on public.website_asset_versions for insert to authenticated with check (status in ('draft', 'pending_review') and storage_bucket = 'website-assets-private' and uploaded_by_user_id = auth.uid() and exists (select 1 from public.website_assets wa where wa.id = website_asset_versions.asset_id and public.can_edit_client_website(wa.website_id)));
drop policy if exists "website_asset_versions_update_admin" on public.website_asset_versions;
create policy "website_asset_versions_update_admin" on public.website_asset_versions for update to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
drop policy if exists "website_asset_versions_delete_draft" on public.website_asset_versions;
create policy "website_asset_versions_delete_draft" on public.website_asset_versions for delete to authenticated using (((status in ('draft', 'pending_review', 'rejected') and uploaded_by_user_id = auth.uid() and exists (select 1 from public.website_assets wa where wa.id = website_asset_versions.asset_id and public.can_edit_client_website(wa.website_id)))) or public.is_platform_admin());

drop policy if exists "website_asset_activity_select" on public.website_asset_activity;
create policy "website_asset_activity_select" on public.website_asset_activity for select to authenticated using (public.can_view_client_website(website_id));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('website-assets-private','website-assets-private',false,26214400,array['image/jpeg','image/png','image/webp','image/gif','image/svg+xml','application/pdf','application/zip','text/plain']) on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('website-assets-public','website-assets-public',true,10485760,array['image/jpeg','image/png','image/webp','image/gif','image/svg+xml']) on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "website_assets_private_select" on storage.objects;
create policy "website_assets_private_select" on storage.objects for select to authenticated using (bucket_id='website-assets-private' and public.can_view_client_website(public.website_storage_path_id(name)));
drop policy if exists "website_assets_private_insert" on storage.objects;
create policy "website_assets_private_insert" on storage.objects for insert to authenticated with check (bucket_id='website-assets-private' and owner_id=auth.uid()::text and public.can_edit_client_website(public.website_storage_path_id(name)));
drop policy if exists "website_assets_private_update" on storage.objects;
create policy "website_assets_private_update" on storage.objects for update to authenticated using (bucket_id='website-assets-private' and public.can_edit_client_website(public.website_storage_path_id(name))) with check (bucket_id='website-assets-private' and public.can_edit_client_website(public.website_storage_path_id(name)));
drop policy if exists "website_assets_private_delete" on storage.objects;
create policy "website_assets_private_delete" on storage.objects for delete to authenticated using (bucket_id='website-assets-private' and (owner_id=auth.uid()::text or public.is_platform_admin()) and public.can_edit_client_website(public.website_storage_path_id(name)));
drop policy if exists "website_assets_public_select" on storage.objects;
create policy "website_assets_public_select" on storage.objects for select to authenticated using (bucket_id='website-assets-public' and public.can_view_client_website(public.website_storage_path_id(name)));
drop policy if exists "website_assets_public_insert_admin" on storage.objects;
create policy "website_assets_public_insert_admin" on storage.objects for insert to authenticated with check (bucket_id='website-assets-public' and public.is_platform_admin());
drop policy if exists "website_assets_public_update_admin" on storage.objects;
create policy "website_assets_public_update_admin" on storage.objects for update to authenticated using (bucket_id='website-assets-public' and public.is_platform_admin()) with check (bucket_id='website-assets-public' and public.is_platform_admin());
drop policy if exists "website_assets_public_delete_admin" on storage.objects;
create policy "website_assets_public_delete_admin" on storage.objects for delete to authenticated using (bucket_id='website-assets-public' and public.is_platform_admin());

insert into public.client_websites (name, slug, live_url, status) values
('Ruth Obenchain Recreation Center','ruth-obenchain-recreation-center','https://ruthobenchainrc.com','active'),
('blyoregon.org','bly-oregon','https://www.blyoregon.org','active'),
('The Bly Outdoor Store','the-bly-outdoor-store','https://theblyoutdoorstore.com','active'),
('Quentin Nichols','quentin-nichols','https://quentinnichols.com','active'),
('Chris Has Deals','chris-has-deals','https://chrishasdeals.com','active'),
('Nichols Tree Care LLC','nichols-tree-care','https://nicholstreecarellc.com','active')
on conflict (slug) do update set name=excluded.name,live_url=excluded.live_url,status=excluded.status,updated_at=now();;
